### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by aaronovz1** [pohly/meta-swupd#6]
Just wondering if this is still active and whether patches will be updated to work with swupd-server 3.7.5?

**Comment by pohly** [comment]
pohly/meta-swupd is inactive.

swupd-server has been replaced (or is in the process of being replaced, not sure exactly what the latest status is) with a re-implementation in Go as part of the Clear Linux mixer tool. Getting that tool to work with Yocto is going to be a significant chunk of work, mostly because Go programs call the kernel directly and thus do not work under pseudo. Mixer would have to be changed to to use glibc calls, which is doable, but was rejected by the upstream maintainers. No next steps are planned for this.

**Comment by aaronovz1** [comment]
So basically meta-swupd is dead and people should find an alternative that is active?

**Comment by pohly** [comment]
You can either wait for someone to pick it up, maintain it yourself (perhaps with others who are interested?) or switch to something else.
